### PR TITLE
Settings in nav drawer

### PR DESCRIPTION
**Pull request by CytoDev**
@jariz Settings are back in the drawer as of this merge.

### CODE REVIEW

**Comment by jariz** [comment]
Could it be possible to show it completely at the bottom? 😅

**Comment by CytoDev** [comment]
@jariz Check it

**Comment by jariz** [comment]
Perfect, only needs the separator on the top again (I think).

**Comment by CytoDev** [comment]
I'm currently waiting for my train, so I'll take a look at it when I'm seated.

**Comment by jariz** [comment]
@CytoDev awesome, you're the best

**Pull request merged**
