### PR TITLE
Updated strings

### PR DESCRIPTION
**Pull request by GijsTimmers**
- Spelling: koppeltekens, samenvoegingen, Engelse sisklanken
- Stijl: aangepast op wat gangbaar is in de FOSS-wereld; zie ook
  https://localize.drupal.org/node/2314

### CODE REVIEW

**Comment by CytoDev** [comment]
Merged into newNavDrawer as of [#ce1a213](https://github.com/jariz/Dumpert/commit/ce1a2138c0759acb90f129dbeaa66787828b6afe).

**Comment by KeizerDev** [comment]
@GijsTimmers so, you can close this now. I guess

**Comment by GijsTimmers** [comment]
No need to hurry... I'll let @jariz decide

**Comment by jariz** [comment]
If it's already merged into newNavDrawer then there's no point in keeping this PR open because it's part of PR #37 now.

**Pull request closed without merging**
