### PR TITLE
New nav drawer + Login/logout functionality + various fixes and improvements

### PR DESCRIPTION
**Pull request by CytoDev**
Some bugs may remain since I did not test _everything_, but it seems to be working like a charm on my machine.  
  
@jariz
It's up to you to merge this branch.  
  
Some screenshots of the new drawer/login/settings:

### CODE REVIEW

**Comment by CytoDev** [comment]
@jariz I'm going to leave it to you to merge this. A lot of things have changed, and I didn't watch the main branch as close as you did.

**Comment by CytoDev** [comment]
Some screenshots of the new drawer:

**Comment by CytoDev** [comment]
@jariz
It's up to you to merge this branch.

Some screenshots of the new drawer/login/settings:

**Comment by jariz** [comment]
Damn, you came through!
I'll test it on my device in an hour, will keep you up to date.

**Comment by CytoDev** [comment]
I always come through. ;)

Commenting and voting will be a charm from here on.

**Comment by CytoDev** [comment]
@jariz Just implemented a few nice to haves. Filter to only show positively kudo'd items, and a button that opens the device's data usage page.

**Comment by CytoDev** [comment]
Screenshots van de nicetohaves:  
  
  
  
Aanzet naar kudo's uitdelen en reaguren. Kudo's uitdelen werkt momenteel enkel op reaguursels, kudo's voor items worden doorgestuurd naar een plaatje van een t-shirt... (wtf Dumpert?)

**Comment by KeizerDev** [comment]
Lol, the next time you should stop working from this branch and create a new one and make it depend on this branch, otherwise we get a pretty big PR and it will be pretty for us to contribute too. :sweat_smile:

**Comment by CytoDev** [comment]
@KeizerDev yah, I forgot to branch off... I thought I did, but it was too late to undo and reup to another branch when I found out I didn't. I should really find/create something that watches my commit messages and notifies me when I try to commit something along the lines of "function x" to branch y...

**Comment by jariz** [comment]
Few questions/remarks:

- Why is there a whole extra bar with buttons that might as well could've been added to the actionbar?
- Does ItemActivity really need a 'settings' button in its actionbar?
- Why is 'categories' in lowercase, is that label even necessary?
- Design for actions on comments could also be a lot better, would like something [similar to reddit sync](https://i.imgur.com/SLgEbPu.png) (but I could do that myself after this is merged as well)

Really great job though!

**Comment by KeizerDev** [comment]
@jariz I would want to do something like a design clean up and I can fix your points if @CytoDev agree.

**Comment by jariz** [comment]
Extra remark, why not add voting buttons to the cards as well?
@KeizerDev I recommend you do that after this has merged, as I don't want this insane PR to get even bigger :stuck_out_tongue:

**Comment by CytoDev** [comment]
@jariz  
The bar with buttons seems to be more intuitive than hiding it in an overflow menu. Keep in mind that most android phones have a width of about 480px. Either the title becomes unreadable, or the actions get pushed into the overflow. As for settings in the ItemActivity. Yes, it's needed. You will probably spend more time in those activities than in the main activity. Changing settings is something that should be a universal possibility. At least for user-friendliness.  
  
Why categories is lower case... Well, make it caps if you want? Not any reason in particular. Is it really necessary? - It isn't, but it adds a certain professional touch to the drawer. Dumpert has these categories as small links, so why not empathise on them? It should also be noted that the categories have the possibility of combinations with the two other menu items (not implemented, but easily done). As far as design goes. It was not my first concern. The images and layout is just a frame to test the actual functionality.  
  
Why no voting on cards? - Voting doesn't work yet. ( #35) So I did not bother to do that yet. Besides, you need a String that can only be extracted from the comments at this time.  
  
@KeizerDev  
Go ahead. When this big blob of clutter is merged.

**Comment by jariz** [comment]
Fair enough. Agreed.
@KeizerDev what are you planning on redesigning exactly, because I'm planning to do the same.

**Comment by KeizerDev** [comment]
@jariz Yeah, that's why I waited with doing it :stuck_out_tongue_winking_eye:

**Comment by KeizerDev** [comment]
@jariz what I was planning(/saw so far) to do
- Replace the comment buttons in a more material design way (Like the youtube app does).
- Move settings back to drawer
- Redesign the comment blocks.
  
**Optional (some of them are really imho):**
- Replace drawer with https://github.com/mikepenz/MaterialDrawer (To get a more structure and profile header will look better. Check out https://raw.githubusercontent.com/mikepenz/MaterialDrawer/develop/DEV/github/screenshots2.jpg (The one in the middle, with a white background)). 
- Remove `com.github.johnkil.android-robototextview:robototextview:2.4.3` and replace all of it for a normal one.

**Some where I need your opinion for:** 
- Option: Share direct video link or share Dumpert link (First enable it in settings).
- Option: Download video's next to share button (First enable it in settings).

cc: @CytoDev

**Comment by CytoDev** [comment]
@KeizerDev  
 - Go right ahead, I only placed them for testing purposes.
 - [Makes sense](https://www.google.com/design/spec/patterns/settings.html#settings-placement)
 - Redesigning is a broad concept, isn't it?
 - We just moved away from the MaterialDrawer...
 - robototextview... yeah, I don't see the point of it either.
 - why would you want to share a direct video link?
 - why would you want to download a video?

**Comment by KeizerDev** [comment]
3. True, I'll just try some things out and show it first to you guys.
4. Okay, now I get it. I'll redesign it either way. Also here, I'll just make it look better in my eyes and than discuss further about it with you guys.
5. I don't actually see the point of using it. I don't think it looks prettier when adding it, as I said, that's pretty imho.
6. When sending something using WhatsApp to an iOS user, it first have to load the page and than you're able to view it on a non mobile website. So it would be a lot prettier to just load the video and nothing more. 
7. Same reason as 6. and that can be handy when you want to send it directly

**Comment by CytoDev** [comment]
1. resolved.  
2. resolved?  
3. the point in using this is that we have more control over it. Besides, issues #16 and #22 where caused by that same drawer. Even some other exceptions occurred when I was trying to remove it from the project. All of which have been resolved by switching to a drawer actually designed by google.  
4. personal preferences. I hate it when people send me a link to a video directly.  
5. I can find myself in this, but I don't believe it's something we should pursue as of the next release.

**Comment by jariz** [comment]
- RobotoTextView was used because... I wanted Roboto on < 5.0 devices. (which is weird apparently?)
Typography is important and the goal from the start with this project was to keep the visual parts the same across all versions of android. If you can still keep that, then you may get rid of it.
- Settings back in drawer is something I want as well. (wasn't too happy that it was removed)
- I agree with @CytoDev that there's no point in sharing a direct video link.
- Downloading the video might be useful for offline usage, but I wouldn't make that part of your redesign.
- I'm actually pretty OK with how the account part looks in the navdrawer, we don't have a way of switching accounts, and we have no avatars, so there's nothing much to display there than we already have imo.

**Comment by KeizerDev** [comment]
Yeah, I'll dig in it asap. What was your plan about the redesign? @jariz

**Comment by jariz** [comment]
Think you pretty much covered what I wanted to do lol.
Few more questions to you @KeizerDev :
- Think the bar beneath audio/video/images with the kudo buttons could use a little love as well though, not sure if you were planning on getting to that, else I'll look into it.
- Could you put the settings in the bottom of the nav drawer like it was before?

What I'm planning to do:

- I'll probably remove the categories label in the nav drawer. (sorry, but I hate it and think it's unneeded)
- Experiment a bit with trying to make the account part look nicer in the navdrawer.
- I was planning on messing around a bit with [AppIntro](https://github.com/PaoloRotolo/AppIntro) and see if I can make a nice introduction for new users.
- Would like to make it possible to 'swipe' away the ItemActivity like in reddit sync (but that's kind of outside the scope)

**Comment by CytoDev** [comment]
@jariz, I constantly find myself trying to pull a video down like the YouTube app does... It really needs to be implemented.

**Comment by KeizerDev** [comment]
@CytoDev 
https://github.com/pedrovgs/DraggablePanel
https://github.com/wuyexiong/android-youtube-drag-layout
http://flavienlaurent.com/blog/2013/08/28/each-navigation-drawer-hides-a-viewdraghelper/

Good luck :stuck_out_tongue_winking_eye:

**Comment by CytoDev** [comment]
@KeizerDev yah, I can't read Chinese. The other links look promising though.

**Pull request merged**
