### PR TITLE
Up the versionName one minor.

### PR DESCRIPTION
**Pull request by CytoDev**
Since we updated a bunch of stuff compared to release 1.1.0 I feel like we need to up the minor to 2. [see](http://semver.org/)

### CODE REVIEW

**Comment by jariz** [comment]
Is everything that's currently implemented on master 100% functional?

**Comment by CytoDev** [comment]
Except voting, yes. Tested on AVD marshmallow and Device lollipop. I'm going to need a hand with voting though. See #35

**Comment by jariz** [comment]
Don't think we can release a new (minor!) version if it has incomplete features.

**Comment by jariz** [comment]
Also youtube idea is cool but not a priority for now.

**Comment by CytoDev** [comment]
It's not a release just yet, is it? This one is stashed so we don't forget... Because I'm forgetful like that :laughing:

**Comment by jariz** [comment]
I'm just a bit anxious on getting it released again. Logging in etc wasn't even supposed to be part of the current milestone. (but that's kinda my fault for merging it into master)
The app lost [1k+ installs since the error + play store removal](https://i.imgur.com/MUlBR2J.png) and I still [get an error report almost every day from 'the' error.](https://i.imgur.com/7rmXfqb.png)
Just a shame really.
But yea, let's not merge this until voting is fixed.

**Comment by CytoDev** [comment]
Wait, what was the IlligalStateException about again? Well yes, you can expect people to install a dysfunctional app. You set the milestone deadline at February something right? Plenty of time to get everything up and running.

**Comment by jariz** [comment]
@CytoDev I'm not blaming them for uninstalling it (obviously), I'm blaming myself for not releasing a version earlier.
You know what, fuck it. Let's just merge this, update the play store version, and keep voting for 1.2.1 or something. I'll hide the buttons for now.

**Pull request merged**
